### ISSUE TITLE
Unity-iOSでのFindAsyncでデータストアのデータを取得時、タイムアウトエラーが返ってきてデータを取得できません

### ISSUE THREAD

**Issue by sensp** [NIFTYCloud-mbaas/ncmb_unity#27]
■環境

<pre>
　▼種別
    Unity , iOS

    ▼SDKバージョン
    Unity 2.2.0

    ▼お問い合せ詳細
    querryのFindAsyncでデータストアのデータを取得しようとしたときに回線が悪い状態で
       タイムアウトエラーが返ってくると、それ以降は回線の状態がよくなってもタイムアウトエラーが
       返ってきてデータを取得できません。
</pre>

■ログ内容

<pre>
【StatusCode】:0
【Error】:NCMB.NCMBException: The request timed out
【ResponseData】:
    NCMB.Internal.NCMBDebug:Log(String) (at Assets/NCMB/Script/NCMBDebug.cs:44)
    NCMB.<Find>c__AnonStorey12:<>m__1E(Int32, String, NCMBException) (at Assets/NCMB/Script/NCMBQuery.cs:571)
    NCMB.Internal.NCMBConnection:_Connection(HttpWebRequest, HttpClientCallback, HttpClientFileDataCallback) (at Assets/NCMB/Script/NCMBConnection.cs:229)
    NCMB.Internal.NCMBConnection:Connect(HttpClientCallback) (at Assets/NCMB/Script/NCMBConnection.cs:113)
    NCMB.NCMBQuery`1:Find(NCMBQueryCallback`1) (at Assets/NCMB/Script/NCMBQuery.cs:570)
    NCMB.<FindAsync>c__AnonStorey11:<>m__1C() (at Assets/NCMB/Script/NCMBQuery.cs:550)

【NCMBConnection.cs -> _Connection(..)メソッド】
 httpResponse = (HttpWebResponse)Httpreq.GetResponse(); //ここで発生します。
</pre>

■原因

<pre>
1)HttpWebRequestインスタンスを確実にAbortしておらず、
　HttpWebRequestの"何かが"残り、WebStreamの読み書きができず
　HttpWebRequestが固まることがあるらしいです。
　（この固まる現象はHttpWebRequestを連続で呼び出すときに発生しやすい）

2)HttpWebRequestクラスは直接TCPコネクションを処理しているわけではありません。
　ServicePointManagerクラスによって管理されているServicePointクラスを介して通信してます。
（更にその先にConnectionGroupやらConnectionクラスがありますが。）
　そのため、もしも通信できないTCPコネクションを持ったServicePointインスタンスが生き続け、HttpWebRequestがそのServicePointばかりを割り当てられた場合、現象のようにエラーになり続けます。
　ですので、破棄されていないServicePointインスタンスを使用し続けているのが原因かもしれません。
</pre>

■修正案

<pre>
・MaxIdleTime = ServicePoint オブジェクトに関連付けられた接続が閉じられるまでにアイドル状態を持続できる合計時間を取得または設定します。
・各 ServicePoint オブジェクトは、アイドル時間が MaxIdleTime プロパティで指定された時間を超えるまで、インターネット リソースへの接続を維持します
・現在のServicePoint オブジェクトは、アイドル時間が MaxIdleTime プロパティ値 = 900000 長いです。(デフォルト　900秒=15分意味)
</pre>

<pre>
・Unity
  【NCMB/Script/NCMBConnection.cs -> internal HttpWebRequest _returnRequest ()メソッド】追加更新要
    1)Unityでプラットフォーム(iOSのみ)に分岐を作る。(#if UNITY_IOS)
    2)接続が閉じられるまでにアイドル状態を短くします。(MaxIdleTime = 1)
    
    例)
    ：：：：：
　　// ---------------------------------------------------------------------- ここから↓
    #if UNITY_IOS
        req.ServicePoint.MaxIdleTime = 1;　//接続を閉じていないための回避案
    #endif
　　// ---------------------------------------------------------------------- ここまで↑

    return req;
</pre>

以上です。

**Comment by oonoyosp** [comment]
<回避案補充>
・req.ServicePoint.MaxIdleTime = 1の修正案がたまに出来ない現状が発生するので下記の回避案を提出します。

・現在のWebRequestのタイムアウト設定値
```
private static readonly int REQUEST_TIME_OUT = 10000; //10秒意味
：：：：：
req.Timeout = REQUEST_TIME_OUT;
```

・修正案
```
WebRequestのタイムアウト(最初の応答が返るまでのタイムアウト)を"-1"に設定する事で
回線が悪い状態でタイムアウトエラーが返ってくると Rrequest timed out【既存】 -> Connection timed out【更新】に変わります。
それ以降は回線の状態がよくなるとデータを取得出来ます。
問題のRrequest timed outによるHttpWebRequestが固まることを回避する事が出来ます。
```

・Unity
```
【NCMB/Script/NCMBConnection.cs -> internal HttpWebRequest _returnRequest ()メソッド】更新
- Unityでプラットフォーム(iOSのみ)に分岐を作る。(#if UNITY_IOS)
例)
：：：：：
// ---------------------------------------------------------------------- ここから↓
#if UNITY_IOS
req.Timeout = -1;　//接続を閉じていないための回避案
#endif
// ---------------------------------------------------------------------- ここまで↑

return req;
```
参考ください。
