### ISSUE TITLE
【要望】UnitySDKではプッシュ通知を登録する際、絞り込み配信ができるようにする

### ISSUE THREAD

**Issue by ncmbadmin** [NIFTYCloud-mbaas/ncmb_unity#31]
# 内容

* 現在UnitySDKで端末絞り込みできるのはPushTiAndroid/PushToIoSのみ
* searchConditionを指定できるようにすることで、配信端末絞り込みが簡単にできるようになります
* 詳細実装方法はAndroid/iOSで実施している方法でいいではないかと思います

# 参考

iOSで行っている実装

http://mb.cloud.nifty.com/assets/sdk_doc/ios/doc/html/Classes/NCMBPush.html#//api/name/setSearchCondition:

Androidで行っている実装
http://mb.cloud.nifty.com/assets/sdk_doc/android/javadoc/index.html
⇒　NCMBPush -> setSearchConditionメソッド

**Comment by hocnguyen** [comment]
This issue is similar with issue #21 
For issue 21, I had fixed and create p-r at #29
Please help me confirm!

**Comment by gs0zk1** [comment]
Merge対応したのでcloseします。
