### ISSUE TITLE
iOS10の端末で開封率が反映されない

### ISSUE THREAD

**Issue by oonoyosp** [NIFTYCloud-mbaas/ncmb_unity#56]
## 不具合の概要(Description of bug)

iOS10の端末で開封率が反映されません。

- SDKのバージョン(SDK version)
ncmb_unity 3.0.0
Unity2017.1.0b1 及び　Unity5.6.0f3
- 不具合が発生した環境(Environment requirement)

- 不具合を再現させる手順・サンプルコード(Step for Reproduce bug / Sample code)
http://mb.cloud.nifty.com/doc/current/push/openrates_unity.html#プッシュ通知の開封通知を行う
NCMBSettingsのInspector内「useAnalytics」にチェックを入れて、プッシュ通知から起動しても、反映されませんでした。
- エラーメッセージ(Error messages)

**Comment by n0guch1** [comment]
## 調査結果

iOS10でのSystemInfo.operatingSystemの形式が変わりIndexOf ("iPhone")に該当しなかったため
`Debug.Log(SystemInfo.operatingSystem) // iOS 10.0.1`
https://github.com/NIFTYCloud-mbaas/ncmb_unity/blob/v3.0.0/ncmb_unity/Assets/NCMB/NCMBAnalytics.cs#L46

## 修正案

```
if (Application.platform == RuntimePlatform.Android) {
  // Android
}
else if (Application.platform == RuntimePlatform.IPhonePlayer) {
  // iOS
}
```
または
```
#if UNITY_ANDROID
  // Android
#elif UNITY_IOS
  // iOS
#endif
```
